import type {
  AppUser,
  Course,
  FeishuDepartment,
  FeishuEmployee,
  FeishuOrganization,
  LearningPath,
  QuizQuestion,
  ServiceArticle,
  TrainingRecord,
  VideoAnalytics,
} from '@/lib/types'

export const demoUsers: Record<'employee' | 'admin', AppUser> = {
  employee: {
    id: 'user-chen-yu',
    name: '陈屿',
    englishName: 'Evan Chen',
    email: 'chenyu@example.com',
    departmentId: 'department-product',
    departmentName: '产品中心',
    role: 'superAdmin',
    active: true,
    joinedAt: '2026-08-11',
  },
  admin: {
    id: 'user-lin-xi',
    name: '林溪',
    englishName: 'Lynn Lin',
    email: 'linxi@example.com',
    departmentId: 'department-hr',
    departmentName: '人力资源部',
    role: 'superAdmin',
    active: true,
    joinedAt: '2024-03-18',
  },
}

const courses: Course[] = [
  {
    id: 'course-onboarding',
    pathId: 'path-onboarding',
    order: 1,
    title: '新人入职说明',
    summary: '用一段视频了解公司、入职流程以及第一周需要完成的事项。',
    category: '新员工必看',
    durationMinutes: 12,
    status: 'inProgress',
    progress: 68,
    completedUnits: 0,
    unitCount: 1,
    units: [
      {
        id: 'unit-onboarding-video',
        courseId: 'course-onboarding',
        order: 1,
        title: '新人入职说明视频',
        description: '了解公司、入职流程以及第一周需要完成的事项',
        type: 'video',
        durationMinutes: 12,
        status: 'inProgress',
        progress: 68,
        hasQuiz: true,
        videoUrl: 'https://storage.googleapis.com/coverr-main/mp4/Mt_Baker.mp4',
      },
    ],
  },
]

export const onboardingPath: LearningPath = {
  id: 'path-onboarding',
  title: '新人入职说明',
  summary: '观看一段入职说明视频，快速了解公司和入职流程。',
  assignedAt: '2026-08-11',
  dueAt: '2026-08-18',
  progress: 68,
  completedCourses: 0,
  courseCount: courses.length,
  courses,
}

export const questionBank: QuizQuestion[] = [
  {
    id: 'question-1',
    courseId: 'course-onboarding',
    categoryId: 'onboarding-basics',
    type: 'single',
    prompt: '游戏产品从想法走向长期运营，通常遵循哪一组阶段？',
    options: [
      { id: 'a', label: '市场调研、研发制作、全球发行、产品运营' },
      { id: 'b', label: '产品运营、市场调研、全球发行、研发制作' },
      { id: 'c', label: '全球发行、研发制作、市场调研、产品运营' },
      { id: 'd', label: '研发制作、产品运营、市场调研、全球发行' },
    ],
    correctOptionIds: ['a'],
    explanation: '培训讲义将产品生命周期概括为市场调研、研发制作、全球发行和产品运营四个阶段。',
    difficulty: 'easy',
  },
  {
    id: 'question-2',
    courseId: 'course-onboarding',
    categoryId: 'onboarding-basics',
    type: 'multiple',
    prompt: '以下哪些属于培训讲义中提到的常见游戏变现方式？',
    options: [
      { id: 'a', label: '广告变现' },
      { id: 'b', label: '应用内购买（IAP）' },
      { id: 'c', label: '订阅制' },
      { id: 'd', label: '向员工收取入职费用' },
    ],
    correctOptionIds: ['a', 'b', 'c'],
    explanation: '广告、应用内购买和订阅制是讲义列出的三类常见变现方式。',
    difficulty: 'medium',
  },
  {
    id: 'question-3',
    courseId: 'course-onboarding',
    categoryId: 'onboarding-collaboration',
    type: 'trueFalse',
    prompt: '推进需求时，可以绕过项目协作渠道，私下找熟悉的同事直接处理。',
    options: [
      { id: 'true', label: '正确' },
      { id: 'false', label: '错误' },
    ],
    correctOptionIds: ['false'],
    explanation: '需求、进度与结论应在项目约定的正式渠道中同步，避免绕过流程造成信息不对称。',
    difficulty: 'easy',
  },
  {
    id: 'question-4',
    courseId: 'course-onboarding',
    categoryId: 'onboarding-collaboration',
    type: 'single',
    prompt: '发现任务可能延期或出现质量风险时，最合适的做法是什么？',
    options: [
      { id: 'a', label: '等到截止日再说明' },
      { id: 'b', label: '立即同步负责人，并提出可执行的备选方案' },
      { id: 'c', label: '只在私聊中告诉一位同事' },
      { id: 'd', label: '先隐藏风险，避免影响团队情绪' },
    ],
    correctOptionIds: ['b'],
    explanation: '及时上报风险并给出备选方案，能让团队尽早调整资源和计划。',
    difficulty: 'medium',
  },
  {
    id: 'question-5',
    courseId: 'course-onboarding',
    categoryId: 'onboarding-company',
    type: 'single',
    prompt: '乐堡互娱主要专注于哪项业务？',
    options: [
      { id: 'a', label: '全球手机游戏研发与发行' },
      { id: 'b', label: '企业硬件制造' },
      { id: 'c', label: '线下主题乐园运营' },
      { id: 'd', label: '办公软件外包' },
    ],
    correctOptionIds: ['a'],
    explanation: '新人培训资料介绍，乐堡互娱专注全球手机游戏研发与发行。',
    difficulty: 'easy',
  },
  {
    id: 'question-6',
    courseId: 'course-onboarding',
    categoryId: 'onboarding-company',
    type: 'multiple',
    prompt: '以下哪些角色会参与游戏项目协作？',
    options: [
      { id: 'a', label: '策划与美术' },
      { id: 'b', label: '前后端与测试' },
      { id: 'c', label: '项目管理、社区与客服' },
      { id: 'd', label: '与项目无关的外部个人账号' },
    ],
    correctOptionIds: ['a', 'b', 'c'],
    explanation: '游戏项目依靠策划、研发、测试、美术、项目管理、社区、客服等不同角色共同交付。',
    difficulty: 'medium',
  },
  {
    id: 'question-7',
    courseId: 'course-onboarding',
    categoryId: 'onboarding-security',
    type: 'trueFalse',
    prompt: '岗位需要安装新软件时，应通过 IT 或公司规定的审批流程申请。',
    options: [{ id: 'true', label: '正确' }, { id: 'false', label: '错误' }],
    correctOptionIds: ['true'],
    explanation: '员工手册要求公司设备只安装 IT 提供或批准的软件，特殊需要应联系 IT。',
    difficulty: 'easy',
  },
  {
    id: 'question-8',
    courseId: 'course-onboarding',
    categoryId: 'onboarding-first-week',
    type: 'multiple',
    prompt: '新人第一周建议完成哪些事项？',
    options: [
      { id: 'a', label: '检查账号、设备与岗位权限' },
      { id: 'b', label: '认识直属负责人和核心协作者' },
      { id: 'c', label: '阅读员工手册并完成培训测评' },
      { id: 'd', label: '未经确认直接修改线上数据' },
    ],
    correctOptionIds: ['a', 'b', 'c'],
    explanation: '第一周应先建立工作基础：可用的账号设备、清晰的协作关系和对制度的基本了解。',
    difficulty: 'easy',
  },
]

export const serviceArticles: ServiceArticle[] = [
  {
    id: 'service-leave',
    category: 'HR',
    title: '休假与请假怎么申请',
    summary: '年假、病假、事假、调休与请假审批的制度要点。',
    type: 'article',
    updatedAt: '2026-08-01',
    tags: ['请假', '年假', '病假', '事假', '调休', '审批'],
    source: '《员工手册 V2026.08.01》第 4 章',
    sections: [
      { title: '申请原则', items: ['请假应在公司考勤系统中提交，并按照假期类型上传所需材料。', '除紧急情况外，应先完成审批再休假；紧急情况消除后应立即补交申请。', '休假结束后如需续假，应再次提交申请并获得批准。'] },
      { title: '病假与事假', items: ['病假按照员工手册要求提供有效医疗证明；无法提供有效证明的，按事假处理。', '事假应说明具体事由，获批准后方可休假。', '考勤与休假最终以系统中审批通过的数据为准。'] },
      { title: '调休提醒', items: ['休息日加班须履行加班审批，获批后由公司统筹安排调休。', '调休最小申请单位为 0.5 天，具体有效期以员工手册及系统余额为准。'] },
    ],
  },
  {
    id: 'service-benefits',
    category: 'HR',
    title: '员工福利与商业保险',
    summary: '薪酬发放、商业保险、餐补及成长类福利的说明。',
    type: 'article',
    updatedAt: '2026-08-01',
    tags: ['薪酬', '保险', '餐补', '团建', '购书', '成长基金', '健身'],
    source: '《员工手册 V2026.08.01》第 5 章',
    sections: [
      { title: '补充保障', items: ['公司按照制度为符合条件的员工提供补充商业保险，具体保障范围以当期保险方案为准。', '福利资格、起止时间和离职结算规则以员工手册及人力资源部通知为准。'] },
      { title: '日常与成长福利', items: ['员工手册列明早餐与晚餐补助、迎新福利和团队建设支持。', '购书基金、成长基金、健身基金与交通补助按对应申请规则执行。', '报销或领取前请在飞书查看最新额度、适用范围与材料要求。'] },
    ],
  },
  {
    id: 'service-access',
    category: '行政',
    title: '会议室与办公环境使用指南',
    summary: '会议室预订、办公安全与公共设施使用规则。',
    type: 'article',
    updatedAt: '2026-08-01',
    tags: ['会议室', '办公环境', '安全', '公共设施'],
    source: '《员工手册 V2026.08.01》第 10 章',
    sections: [
      { title: '会议室预订', items: ['会议室通过飞书提前预订，遵循“先订先得”。', '超过预定开始时间 15 分钟仍无人使用，会议室会重新开放。', '使用后复位设备设施，关闭电源、照明与空调；会议室内禁止用餐。'] },
      { title: '办公环境与安全', items: ['爱护公共设备，发生故障及时通知行政或维修部门，不自行拆装。', '公共区域设备和家具未经行政确认不得搬移。', '办公区域禁止吸烟，包括电子烟。'] },
    ],
  },
  {
    id: 'service-expense',
    category: '行政',
    title: '差旅与费用报销',
    summary: '出差申请、费用真实性与财务报销的基本要求。',
    type: 'article',
    updatedAt: '2026-08-01',
    tags: ['差旅', '报销', '发票', '财务'],
    source: '《员工手册 V2026.08.01》第 3.9 节与第 9 章',
    sections: [
      { title: '出差前', items: ['短期公务出差应提前履行公司规定的申请审批流程。', '确认任务、地点、行程和费用预算；未经批准的个人安排不作为公司出差费用。'] },
      { title: '报销要求', items: ['报销人对费用的真实性、合理性和合规性负责。', '保存并提交符合财务要求的票据与证明材料，按照公司报销流程审批。', '若制度与财务最新通知不一致，以公司最新发布的流程为准。'] },
    ],
  },
  {
    id: 'service-vpn',
    category: 'IT',
    title: '账号、密码与办公网络安全',
    summary: '邮箱密码、文件共享、网络使用与信息安全要求。',
    type: 'article',
    updatedAt: '2026-08-01',
    tags: ['密码', '邮箱', '网络', '文件', '信息安全'],
    source: '《员工手册 V2026.08.01》第 11 章',
    sections: [
      { title: '账号与密码', items: ['首次使用员工邮箱时修改初始密码，并妥善保管。', '邮箱密码不少于 10 位，混合大小写字母、数字和特殊字符，且不得与历史前 3 个密码相同。'] },
      { title: '文件与网络', items: ['重要工作文档使用公司规定的存储空间和公司账号共享。', '公司设备中不存放私人文件和信息，不利用公司网络从事违法或与工作无关的大量下载。', '发现可疑文件、病毒或账号异常时立即停止操作并联系 IT。'] },
    ],
  },
  {
    id: 'service-device',
    category: 'IT',
    title: '设备故障与软件申请',
    summary: '公司设备保管、软件安装、故障报修和资产申请规则。',
    type: 'article',
    updatedAt: '2026-08-01',
    tags: ['电脑', '软件', '权限', '设备', '资产'],
    source: '《员工手册 V2026.08.01》第 10.7 节与第 11 章',
    sections: [
      { title: '设备与软件', items: ['公司计算机由登记使用人负责保管，不自行拆卸、更换配件或添加私人硬件。', '只安装 IT 提供或批准的操作系统、办公软件与安全软件；特殊软件需求联系 IT。', '设备故障及时报修，不由非维修人员拆装。'] },
      { title: '资产领用与异常', items: ['领用资产须提交申请，经审批并收到行政或 IT 通知后领取和确认。', '资产不得私自转借；发生丢失或被盗时立即通知行政或 IT。', '归还、调拨与赔偿按照资产管理制度和实际审批结果执行。'] },
    ],
  },
]

export const trainingRecords: TrainingRecord[] = [
  ['陈屿', '产品中心', 'inProgress', 72, 86, 2],
  ['周然', '产品中心', 'completed', 100, 92, 1],
  ['沈知夏', '研发中心', 'completed', 100, 96, 1],
  ['方恬', '研发中心', 'inProgress', 48, 78, 2],
  ['顾川', '商业化中心', 'notStarted', 0, undefined, 0],
  ['陆遥', '商业化中心', 'overdue', 63, 74, 3],
  ['蒋宁', '用户运营部', 'completed', 100, 88, 2],
  ['叶舟', '用户运营部', 'inProgress', 35, undefined, 0],
  ['唐语', '财务部', 'completed', 100, 90, 1],
  ['梁安', '人力资源部', 'completed', 100, 94, 1],
  ['邱雨', '产品中心', 'inProgress', 82, 84, 2],
  ['许峥', '研发中心', 'notStarted', 0, undefined, 0],
].map(([name, department, status, videoProgress, bestScore, attempts], index) => ({
  userId: index === 0 ? demoUsers.employee.id : `record-user-${index + 1}`,
  userName: String(name),
  departmentName: String(department),
  pathTitle: '新员工入职学习路径',
  courseTitle: '新人入职说明',
  assignedAt: `2026-08-${String(1 + (index % 7)).padStart(2, '0')}`,
  dueAt: `2026-08-${String(8 + (index % 7)).padStart(2, '0')}`,
  status: status as TrainingRecord['status'],
  completedAt: status === 'completed' ? `2026-08-${String(6 + (index % 7)).padStart(2, '0')}` : undefined,
  videoProgress: Number(videoProgress),
  bestScore: bestScore === undefined ? undefined : Number(bestScore),
  attempts: Number(attempts),
}))

export const feishuDepartments: FeishuDepartment[] = [
  { id: 'od-hr', name: '人力资源部' },
  { id: 'od-product', name: '产品中心' },
  { id: 'od-engineering', name: '研发中心' },
  { id: 'od-commercial', name: '商业化中心' },
  { id: 'od-operations', name: '用户运营部' },
  { id: 'od-finance', name: '财务部' },
]

export const feishuEmployees: FeishuEmployee[] = trainingRecords.map((record, index) => {
  const department = feishuDepartments.find((item) => item.name === record.departmentName)
  return {
    id: record.userId,
    name: record.userName,
    email: `employee${index + 1}@example.com`,
    departmentIds: department ? [department.id] : [],
    departmentName: record.departmentName,
  }
})

export const demoFeishuOrganization: FeishuOrganization = {
  source: 'demo',
  departments: feishuDepartments,
  employees: feishuEmployees,
  syncedAt: '2026-08-14T15:30:00+08:00',
}

export const videoAnalytics: VideoAnalytics[] = [
  {
    id: 'unit-onboarding-video',
    title: '新人入职说明视频',
    assigned: 48,
    started: 43,
    completed: 38,
    averageWatchMinutes: 10.8,
    averageProgress: 89,
    lastWatchedAt: '2026-08-14T10:42:00+08:00',
    buckets: [
      { label: '0–10%', value: 2 },
      { label: '10–25%', value: 1 },
      { label: '25–50%', value: 1 },
      { label: '50–75%', value: 1 },
      { label: '75–90%', value: 4 },
      { label: '90–100%', value: 38 },
    ],
  },
]

export const weeklyCompletionTrend = [
  { date: '08/08', completed: 5, started: 12 },
  { date: '08/09', completed: 8, started: 18 },
  { date: '08/10', completed: 11, started: 24 },
  { date: '08/11', completed: 15, started: 31 },
  { date: '08/12', completed: 21, started: 37 },
  { date: '08/13', completed: 27, started: 41 },
  { date: '08/14', completed: 31, started: 43 },
]

export const departmentCompletion = [
  { department: '人力资源部', rate: 92 },
  { department: '用户运营部', rate: 84 },
  { department: '产品中心', rate: 78 },
  { department: '研发中心', rate: 71 },
  { department: '商业化中心', rate: 63 },
]
